### ISSUE TITLE
MDAnalysis error

### ISSUE THREAD

**Issue by krogala** [zoecournia/DREAMM#1]
Dear Developers,

I am very excited to try out DREAMM, but I've been having some challenges in getting it to run — perhaps you can suggest some ideas.

I followed the conda installation instructions, and the python version that got installed out-of-the-box is v3.7.9.

```
(dreamm) rogala@xxx:DREAMM$ dreamm --input heavy.pdb --chain A --database uniclust/uniclust30_2018_08/ --processes 32

/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/Bio/SubsMat/__init__.py:131: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  BiopythonDeprecationWarning,
Traceback (most recent call last):
  File "/SOFTWARE/DREAMM/dreamm/dreamm.py", line 12, in <module>
    from ML.extract_features import featurizer
  File "/SOFTWARE/DREAMM/dreamm/ML/__init__.py", line 1, in <module>
    from .extract_features import * 
  File "/SOFTWARE/DREAMM/dreamm/ML/extract_features.py", line 20, in <module>
    import MDAnalysis as mda
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/MDAnalysis/__init__.py", line 191, in <module>
    from .lib import log
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/MDAnalysis/lib/__init__.py", line 34, in <module>
    from . import transformations
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/MDAnalysis/lib/transformations.py", line 198, in <module>
    from .mdamath import angle as vecangle
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/MDAnalysis/lib/mdamath.py", line 49, in <module>
    from . import util
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/MDAnalysis/lib/util.py", line 217, in <module>
    from ._cutil import unique_int_1d
  File "MDAnalysis/lib/_cutil.pyx", line 1, in init MDAnalysis.lib._cutil
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by zoecournia** [comment]
Hi
You can try our web server version.
Https://dreamm.ni4os.eu
Zoe

**Comment by krogala** [comment]
Thank you, Zoe — I'll check it out!

**Comment by AChatzigoulas** [comment]
Hello,

seems like a compatibility issue with the numpy version. What is your numpy version? Can you please try

```pip install --upgrade numpy ```

If the error still persists can you please send me the output of the commands:
```pip list```
```conda list```

**Comment by krogala** [comment]
Thanks @AChatzigoulas — upgrading numpy definitely fixed that one error, and now the program runs. But it ends up stuck on different error now. Thanks for looking into this!

```
(dreamm) rogala@??:DREAMM$ dreamm --input file.pdb --chain A --database /DATABASES/uniclust/uniclust30_2018_08/ --processes 32
 
/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/Bio/SubsMat/__init__.py:131: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  BiopythonDeprecationWarning,
Selecting Chains...
A 
2022-01-14 01:11:58,049 - moleculekit.molecule - INFO - Removed 7024 atoms. 764 atoms remaining in the molecule.
protein and chain A 
Preparing Protein...
2022-01-14 01:11:58,049 - moleculekit.tools.preparation - WARNING - proteinPrepare has been deprecated in favor of the systemPrepare function and will soon be removed. Please look at the documentation of systemPrepare for more information.
Traceback (most recent call last):
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/moleculekit/tools/preparation.py", line 662, in systemPrepare
    from pdb2pqr.config import VERSION
ModuleNotFoundError: No module named 'pdb2pqr.config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DREAMM/dreamm/dreamm.py", line 54, in <module>
    sys.exit(main(sys.argv))
  File "/DREAMM/dreamm/dreamm.py", line 39, in main
    featurizer(args.input, args.chain, args.database, args.processes)
  File "/DREAMM/dreamm/ML/extract_features.py", line 105, in featurizer
    mol = proteinPrepare(mol, pH=7.0, returnDetails=False)
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/moleculekit/tools/preparation.py", line 497, in proteinPrepare
    _logger_level=_loggerLevel,
  File "/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/moleculekit/tools/preparation.py", line 665, in systemPrepare
    "pdb2pqr not installed. To use the system preparation features please do `conda install pdb2pqr -c conda-forge`"
ImportError: pdb2pqr not installed. To use the system preparation features please do `conda install pdb2pqr -c conda-forge`
```

So I ran `conda install pdb2pqr -c conda-forge` as requested. And here's the follow-up error:

```
(dreamm) rogala@xxx:DREAMM$ dreamm --input r064v5_heavy_sec2.pdb --chain A --database /DATABASES/uniclust/uniclust30_2018_08/ --processes 32
/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/Bio/SubsMat/__init__.py:131: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  BiopythonDeprecationWarning,
Traceback (most recent call last):
  File "/DREAMM/dreamm/dreamm.py", line 12, in <module>
    from ML.extract_features import featurizer
  File "/DREAMM/dreamm/ML/__init__.py", line 1, in <module>
    from .extract_features import * 
  File "/DREAMM/dreamm/ML/extract_features.py", line 19, in <module>
    from pdb2pqr.main import mainCommand
ImportError: cannot import name 'mainCommand' from 'pdb2pqr.main' (/ANACONDA3/envs/dreamm/lib/python3.7/site-packages/pdb2pqr/main.py)
```

I also ran `pip install --upgrade pdb2pqr`, but no luck. Below are the outputs you asked for:

```
(dreamm) rogala@xxx:DREAMM$ pip list
Package            Version
------------------ -------------------
biopython          1.78
brotlipy           0.7.0
certifi            2021.10.8
cffi               1.14.6
cftime             1.2.1
charset-normalizer 2.0.10
cryptography       36.0.1
cycler             0.10.0
decorator          4.4.2
docutils           0.17.1
freesasa           2.1.0
GridDataFormats    0.6.0
gsd                2.5.1
idna               3.1
joblib             0.17.0
kiwisolver         1.2.0
lightgbm           2.3.0
matplotlib         3.3.1
MDAnalysis         2.0.0
mlxtend            0.19.0
mmcif-pdbx         2.0.1
mmtf-python        1.1.2
moleculekit        1.0.5
msgpack            1.0.0
netCDF4            1.5.3
networkx           2.5
numpy              1.21.5
olefile            0.46
pandas             1.1.3
pdb2pqr            3.5.0
Pillow             8.0.0
pip                20.2.4
ProDy              1.10.8
propka             3.4.0
pycparser          2.21
pyOpenSSL          21.0.0
pyparsing          2.4.7
PySocks            1.7.1
python-dateutil    2.8.1
pytz               2020.1
requests           2.27.1
scikit-learn       0.23.2
scipy              1.5.2
seaborn            0.11.0
setuptools         50.3.0.post20201006
sip                4.19.24
six                1.15.0
threadpoolctl      2.1.0
tornado            6.0.4
tqdm               4.50.2
urllib3            1.26.8
wheel              0.35.1
```

```
(dreamm) rogala@xxx:DREAMM$ conda list
# packages in environment at /ANACONDA3/envs/dreamm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
biopython                 1.78             py37h7b6447c_0    anaconda
blas                      2.3                    openblas    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1003    conda-forge
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py37h89c1867_1    conda-forge
cffi                      1.14.6           py37h400218f_0  
cftime                    1.2.1            py37heb32a55_0    anaconda
charset-normalizer        2.0.10             pyhd8ed1ab_0    conda-forge
cryptography              36.0.1           py37hf1a17b8_0    conda-forge
curl                      7.71.1               hbc83047_1    anaconda
cycler                    0.10.0                   py37_0    anaconda
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 4.4.2                      py_0    anaconda
docutils                  0.17.1                   pypi_0    pypi
dssp                      3.0.0                hf484d3e_3    salilab
expat                     2.2.10               he6710b0_2    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freesasa                  2.1.0                    pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0    anaconda
glib                      2.56.2               hd408876_0    anaconda
griddataformats           0.6.0              pyhd8ed1ab_0    conda-forge
gsd                       2.5.1            py37hb1e94ed_0    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
hdf4                      4.2.13               h3ca952b_2
hdf5                      1.10.4               hb1b8bf9_0    anaconda
hhsuite                   3.3.0           py37pl5262h21043fe_2    bioconda
htmd-pdb2pqr              2.1.1+htmd.14              py_0    acellera
icu                       58.2                 he6710b0_3    anaconda
idna                      3.1                pyhd3deb0d_0    conda-forge
joblib                    0.17.0                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
kiwisolver                1.2.0            py37hfd86e86_0    anaconda
krb5                      1.18.2               h173b8e3_0    anaconda
lcms2                     2.11                 h396b838_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libblas                   3.9.0                3_openblas    conda-forge
libboost                  1.67.0               h46d08c1_4    anaconda
libcblas                  3.9.0                3_openblas    conda-forge
libcurl                   7.71.1               h20c2e04_1    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
liblapacke                3.9.0                3_openblas    conda-forge
libnetcdf                 4.7.3                hb80b6cc_0    anaconda
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               hbc83047_0    anaconda
libssh2                   1.9.0                h1ba5d50_1    anaconda
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.1.0                h2733197_1    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
lightgbm                  2.3.0            py37he6710b0_0    anaconda
llvm-openmp               12.0.1               h4bd325d_1    conda-forge
lz4-c                     1.9.2                heb0550a_3    anaconda
matplotlib                3.3.1                         0    anaconda
matplotlib-base           3.3.1            py37h817c723_0    anaconda
mdanalysis                2.0.0            py37hcd2ae1e_1    conda-forge
mlxtend                   0.19.0             pyhd8ed1ab_0    conda-forge
mmcif-pdbx                2.0.1                    pypi_0    pypi
mmtf-python               1.1.2                      py_0    conda-forge
moleculekit               1.0.5                    py37_0    acellera
msgpack-python            1.0.0            py37hfd86e86_1    anaconda
msms                      2.6.1                h516909a_0    conda-forge
ncurses                   6.2                  he6710b0_1    anaconda
netcdf4                   1.5.3            py37hbf33ddf_0    anaconda
networkx                  2.5                        py_0    anaconda
numpy                     1.21.5                   pypi_0    pypi
olefile                   0.46                     py37_0    anaconda
openssl                   1.1.1l               h7f98852_0    conda-forge
pandas                    1.1.3            py37he6710b0_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
pdb2pqr                   3.5.0                    pypi_0    pypi
perl                      5.26.2               h14c3975_0    anaconda
pillow                    8.0.0            py37h9a89aac_0    anaconda
pip                       20.2.4                   py37_0    anaconda
prody                     1.10.8           py37h04863e7_0    insilichem
propka                    3.4.0            py37h6531663_2    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py37h22d08a2_1    anaconda
pysocks                   1.7.1            py37h89c1867_4    conda-forge
python                    3.7.9                h7579374_0    anaconda
python-dateutil           2.8.1                      py_0    anaconda
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2020.1                     py_0    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
readline                  8.0                  h7b6447c_0    anaconda
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scikit-learn              0.23.2           py37h0573a6f_0    anaconda
scipy                     1.5.2            py37habc2bb6_0    anaconda
seaborn                   0.11.0                     py_0    anaconda
setuptools                50.3.0           py37hb0f4dca_1    anaconda
sip                       4.19.24          py37he6710b0_0    anaconda
six                       1.15.0                     py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
threadpoolctl             2.1.0              pyh5ca1d4c_0    anaconda
tk                        8.6.10               hbc83047_0    anaconda
tornado                   6.0.4            py37h7b6447c_1    anaconda
tqdm                      4.50.2                     py_0    anaconda
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wheel                     0.35.1                     py_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
```

**Comment by AChatzigoulas** [comment]
I move this issue into  a new one since the original has been solved
